# https://stackoverflow.com/questions/48495663/docker-compose-env-file-not-working

version: '3.8'
services:
  rasa-nlu-server:
    container_name: rasa-nlu-server
    image: rasa-nlu-server:${RASA_NLU_SERVER_TAG}
    build:
      context: .
      dockerfile: ./docker/Dockerfile.rasa_nlu_server
    restart: unless-stopped
    ports:
      - "${RASA_NLU_SERVER_PORT}:${RASA_NLU_SERVER_PORT}"
    environment:
      - RASA_AUTH_TOKEN=${SAPHIR_AUTH_TOKEN}
    volumes:
      - RASA:/RASA
  app:
    container_name: rasa-action-server
    image: rasa-action-server:${RASA_ACTION_SERVER_TAG}
    expose: [$RASA_ACTION_SERVER_PORT]
    volumes:
      - RASA.actions:/RASA/actions
      - RASA.domain.constants:/RASA/domain/constants
volumes:
  RASA:
  RASA.actions:
  RASA.domain.constants:
