# Dockerfile for NVIDIA NeMo image
# Contains STT and TTS with FastAPI interface

ARG BASE_IMAGE="nvcr.io/nvidia/nemo"
# latest tested working version
ARG BASE_IMAGE_HASH="22.05"
ARG BASE_BUILDER_IMAGE_HASH="latest"

FROM ${BASE_IMAGE}:${BASE_BUILDER_IMAGE_HASH} AS builder

WORKDIR /app

# Change back to root user to install dependencies
USER root

COPY ./requirements/nemo-requirements.txt /app

# Install requirements
RUN python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --no-cache-dir --upgrade -U -r /app/nemo-requirements.txt

# make sure we use the virtualenv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./NeMo/ .

FROM ${BASE_IMAGE}:${BASE_IMAGE_HASH} AS runner

# By best practices, don't run the code with root user
USER 1001

CMD [ "python", "-m" , "pytest", "tests/"]

ENV DOCKER_BUILDKIT=1